### ISSUE TITLE
Bot stops tweeting #2

### ISSUE THREAD

**Issue by 1DanielG** [wjakethompson/tidyverse-tweets#2]
Hey, its me again. Bot stopped tweeting since yesterday, last tweet was 17hr ago 03.04.21. Would you mind checking it. Is it still running?

**Comment by wjakethompson** [comment]
The server it runs on is down for maintenance. It should be back online tomorrow sometime. It's on my list to move the bot to Github actions so that this downtime doesn't keep happening. Hopefully I'll get it moved over in the next couple of weeks.
